In [10]:
import numpy as np

In [12]:
#Code for Q1 Numpy defining matrix.

A= np.arange(1, 16).reshape(3, 5)

#Print out dimension, shape, size and datatype 

#dimension:

print(A.ndim)
print()

#shape:

print(A.shape)
print()

#size:

print(A.size)
print()

#datatype:

print(type(A))
print()

#raw output

print(A)

2

(3, 5)

15

<class 'numpy.ndarray'>

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [14]:
#Question 2 code

B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

print(B)
print()
print(C)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [16]:
#Elementwise subtraction

subtract = np.subtract(B, C)

print(subtract)
print()

#Elementwise multiplication

multiply = np.multiply(B, C)

print(multiply)
print()

#Matrix multiplication

matmul = B @ C

print(matmul)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


In [18]:
#matrix calculations: 

print (matmul)
print ()

#exponent:

exponent = np.exp(matmul)

print (exponent)
print()

#minimum value within exponent:

minimum = np.min(exponent)

print(minimum)
print()

#minimum value by row

minrow = exponent.min(axis=1)

print (minrow)
print()

#so first value is minimum value row 1, second row 2, third row 3

mincol = exponent.min(axis=0)

print (mincol)
print()

#so first value is minimum value column 1, second column 2, third column 3

indexval = np.argmin(exponent)

print(indexval)
print()

#Index value is 0 as it is the first element produced in this page.

sum = np.sum(exponent)

print (sum)
print()

#sum of all elements in matrix.

mean = np.mean(exponent)

print(mean)
print()

#mean elements

median = np.median(exponent)

print(median)
print()

#median elements

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]

[[1.62754791e+05 1.62754791e+05 1.62754791e+05]
 [1.06864746e+13 1.06864746e+13 1.06864746e+13]
 [7.01673591e+20 7.01673591e+20 7.01673591e+20]]

162754.79141900392

[1.62754791e+05 1.06864746e+13 7.01673591e+20]

[162754.791419 162754.791419 162754.791419]

0

2.1050208056887135e+21

2.338912006320793e+20

10686474581524.463



In [20]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

#I may have used the wrong prepared matrix for the previous analysis! **TO ASK IF I CAN KEEP THIS**

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [24]:
A[1]

array([ 6,  7,  8,  9, 10])

In [26]:
#We have only provided the 'central array' - as in 1-5 is ommitted as that is row 0, and 11-15 are ommitted as that is row 2.

In [28]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [32]:
for element in np.nditer(A):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [34]:
#using nditer to iterate an array.

In [36]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [38]:
#this code creates a range from 0-29. The reshape command defines the shape as 2, 3, -1. 
#2 sets the array to have two columns, 3 sets the array to have 3 rows, 
#-1 sets the final dimension according to the total number of elements and the other dimensions.
#So: 30/2*3 = 5 

In [40]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


In [42]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [44]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


In [46]:
#defined the function, including verifications for type errors and value errors that return information on function requirements. 

def add_mult_matrices(matrice1, matrice2, operation):
    if not isinstance(matrice1, np.ndarray) or not isinstance(matrice2, np.ndarray):
        raise TypeError("Inputs require 'numpy.ndarray' type")
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation requires 'add' or 'multiply'")
    if operation == 'add':
        if matrice1.shape != matrice2.shape:
            raise ValueError("'add' requires matrices to have the same dimensions")
        return np.add(matrice1, matrice2)
    elif operation == 'multiply':
        if matrice1.shape[1] != matrice2.shape[0]:
            raise ValueError("'multiply' requires matrice1 columns == matrice2 rows")
        return np.dot(matrice1, matrice2)

In [58]:
#Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? 

#You can check if v1 and v2 are views or copies by using the 'base' command as demonstrated in line 50. 
#In this case, v1 returns a 'None' response, meaning it is a copy. 
#v2 returns the original array, meaning it is a view.

#If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

#This is answered in line 52, I believe?

In [60]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [50]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [52]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
